package com.weng.demo.dao.generate.po;

import java.io.Serializable;

public class PlayerDom implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.id
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.player_name
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    private String playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.job
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.level
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.player_name
     *
     * @return the value of player.player_name
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.player_name
     *
     * @param playerName the value for player.player_name
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.job
     *
     * @return the value of player.job
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.job
     *
     * @param job the value for player.job
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.level
     *
     * @return the value of player.level
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.level
     *
     * @param level the value for player.level
     *
     * @mbg.generated Tue Dec 28 16:50:20 CST 2021
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}